ip-monitoring-tool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cp1/', admin.site.urls), #Specifies path to admin webpage
    path('', include('mainapp.urls')), #Specifies path to login webpage
]

mainapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('users/', views.users, name='users'),
    path('settings/', views.settings, name='settings'),
    path('login/', views.login_view, name='login'), 
    path('logout/', views.logout_user, name='logout'),
    path('add_user/', views.add_user, name='add_user'),
    path('sync_interval/', views.update_sync_interval, name='sync_interval'),
    path('add_ip_space/', views.add_ip_space, name='add_ip_space'),
    path('github-action/', views.github_webhook, name='github_actions'),
    path('edit_ip/<int:ip_id>/', views.edit_ip, name='edit_ip'),
    path('delete_ip/<int:ip_id>/', views.delete_ip, name='delete_ip'),
    
    # password change
    path('password_change/', login_required(login_url='login')(auth_views.PasswordChangeView.as_view()), name='password_change'),
    path('password_change/done/', login_required(login_url='login')(auth_views.PasswordChangeDoneView.as_view()), name='password_change_done'), 


    # password reset

    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/done/', never_cache(auth_views.PasswordResetDoneView.as_view()), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', never_cache(auth_views.PasswordResetCompleteView.as_view()), name='password_reset_complete'),


]

mainapp/models.py
from django.db import models


class IPSpace(models.Model):
    ip_space = models.CharField(max_length=50, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.ip_space
    

class SyncInterval(models.Model):
    sync_interval = models.CharField(max_length=25)

    def __str__(self):
        return self.sync_interval

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import IPSpace, SyncInterval
from ipaddress import ip_network, AddressValueError

class LoginForm(forms.Form):
    username = forms.CharField(required=True, min_length=3, widget=forms.TextInput(attrs={'placeholder': 'Enter your username'})) 
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}))

class SyncIntervalForm(forms.ModelForm):
    sync_interval = forms.IntegerField(required=True, min_value=3,max_value=36, widget=forms.NumberInput(attrs={'placeholder': 'Enter sync interval (3-36)'}))

    class Meta:
        model = SyncInterval
        fields = ['sync_interval']

class IPSpaceEditForm(forms.ModelForm):
    class Meta:
        model = IPSpace
        fields = ['ip_space', 'description']
    
class AddIPForm(forms.ModelForm):
    ip_space = forms.CharField(required=True, min_length=3, widget=forms.TextInput(attrs={'placeholder': 'Enter your username'})) 
    description = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}))

    class Meta:
        model = IPSpace
        fields = ['ip_space', 'description']

    def clean_ip_space(self):
        ip_space = self.cleaned_data.get('ip_space')
        
        try:
            ip_network(ip_space)  # This will raise an exception if the IP range is invalid
        except (AddressValueError, ValueError) as e:
            raise forms.ValidationError("Invalid IP address range.")
        
        return ip_space

class AddUserForm(UserCreationForm):
    username = forms.CharField(required=True, min_length=3, widget=forms.TextInput(attrs={'placeholder': 'Enter your username'})) 
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

# Selectbox on the dashboard
class MySelectForm(forms.Form):
    OPTIONS = [
        ('option1', 'All Databases'),
        ('option2', 'Spamhaus'),
        ('option3', 'Blocklist'),
        ('option4', 'CINS'),
        ('option5', 'AbuselIPDB'),
    ]
    
    select_choice = forms.ChoiceField(choices=OPTIONS, widget=forms.Select(attrs={'class': 'form-control'}))

mainapp/views.py
import json
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login
from django.contrib.auth.models import User
from django.core.cache import cache
from .forms import MySelectForm, AddUserForm, AddIPForm, SyncIntervalForm, IPSpaceEditForm
from django.views.decorators.cache import never_cache
from django.contrib.auth.forms import AuthenticationForm
from .models import IPSpace, SyncInterval
from mainapp.utils.utils import generateContext, get_blacklist_from_file, get_user_ip, handle_invalid_login_attempt, get_device_info
from mainapp.utils.custom_decorators import custom_admin_only, custom_authorised_user
import logging
from django.views.decorators.csrf import csrf_exempt
import subprocess
from django.contrib.auth import views as auth_views
from .models import IPSpace
from django.core.exceptions import PermissionDenied


logger = logging.getLogger('ip-monitoring-tool')
deploy_logger = logging.getLogger('deployment')
auth_logger = logging.getLogger('auth')


def edit_ip(request, ip_id):
     ip = get_object_or_404(IPSpace, id=ip_id)

     if request.method == 'POST':
          form = IPSpaceEditForm(request.POST, instance=ip)
          if form.is_valid():
               form.save()
               messages.success(request, "Successfully editted")
               return redirect('settings')  # Redirect to the settings page after editing
          else:
              messages.error(request, "Failed to edit IP space")
     return redirect('settings')

def delete_ip(request, ip_id):
    ip = get_object_or_404(IPSpace, id=ip_id)
    ip.delete()
    messages.success(request, "Successfully deleted IP space")
    return redirect('settings')  # Redirect to the settings page after deletio
        
@never_cache
def login_view(request):
     user_ip = get_user_ip(request)
     device_info = get_device_info(request)
     username = request.POST.get('username', 'Anonymous')
     key = f'login_attempts:{user_ip}'
     attempts = cache.get(key, 1)
     MAX_LOGIN_ATTEMPTS_PER_HOUR = 5

     if request.user.is_authenticated:
          return HttpResponseRedirect('/')
     
     if attempts > MAX_LOGIN_ATTEMPTS_PER_HOUR:
        raise PermissionDenied()
     if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            auth_logger.info(f"200 OK {user_ip} {user} {request.path} {device_info}")
            messages.success(request, "Successfully logged in")
            cache.delete(f'login_attempts:{request.META.get("REMOTE_ADDR")}')
            return HttpResponseRedirect('/')
        else:
            cache.set(key, attempts + 1, 3600)
            handle_invalid_login_attempt(request, attempts, MAX_LOGIN_ATTEMPTS_PER_HOUR, username)
            return HttpResponseRedirect('/login')

     return render(request, 'mainapp/login.html', {})


@custom_authorised_user
def dashboard(request):
     blocklist = get_blacklist_from_file()
     sorted_data = sorted(blocklist, key=lambda x: x['ip'])
     # The if statement gets by posting a selected option contrary to  the http convention.
     if request.method == 'POST':
          form = MySelectForm(request.POST)
          if form.is_valid():
               selected_option = form.cleaned_data['select_choice']
               context = generateContext(request, selected_option, sorted_data, form)

               return render(request, 'mainapp/dashboard.html', context)
     else:
          form = MySelectForm(initial={'select_choice': 'option1'})
          selected_option = form.initial['select_choice']
          context = generateContext(request, selected_option, sorted_data, form)

          return render(request, 'mainapp/dashboard.html', context)
     

@login_required(login_url='login')
def add_ip_space(request):
     user_ip = get_user_ip(request)
     device_info = get_device_info(request)
     username = request.user.username if request.user.is_authenticated else "Anonymous"
     if request.method == 'POST':
          form = AddIPForm(request.POST)
          if form.is_valid():
               form.save()
               logger.info(f"200 OK {user_ip} {username} {request.path} {device_info}")
               messages.success(request, f"Successfully added IP space")
               return HttpResponseRedirect('/')
          else:
            for field, errors in form.errors.items():
                for error in errors:
                     messages.error(request, f"{error}")
                     logger.info(f"Failed to add IP space: {error}")
            logger.error(f"400 Bad request {user_ip} {username} {request.path} {device_info}")

            return HttpResponseRedirect('/')
     form = AddIPForm() 

@custom_admin_only
def add_user(request):
     user_ip = get_user_ip(request)
     device_info = get_device_info(request)
     username = request.user.username if request.user.is_authenticated else "Anonymous"
     if request.method == 'POST':
          form = AddUserForm(request.POST)
          if form.is_valid():
               form.save()
               messages.success(request, "Successfully added user")
               logger.info(f"200 OK {user_ip} {username} {request.path} {device_info}")
               return HttpResponseRedirect('/users')
          else:
            for field, errors in form.errors.items():
                for error in errors:
                     messages.error(request, f"{error}")
            logger.error(f"400 Bad request {user_ip} {username} {request.path} {device_info}")

            return HttpResponseRedirect('/users')
     form = AddUserForm()


@custom_admin_only
def update_sync_interval(request):
     user_ip = get_user_ip(request)
     device_info = get_device_info(request)
     username = request.user.username if request.user.is_authenticated else "Anonymous"
     if request.method == 'POST':
          form = SyncIntervalForm(request.POST)

          if form.is_valid():
               form.save()
               messages.success(request, "Successfully updated Sync Interval")
               logger.info(f"200 OK {user_ip} {username} {request.path} {device_info}")
               return HttpResponseRedirect('/settings')
          else:
            for _, errors in form.errors.items():
                for error in errors:
                     messages.error(request, f"{error}")
            logger.error(f"400 Bad Request {user_ip} {username} {request.path} {device_info}")

            return HttpResponseRedirect('/settings')

     return HttpResponseRedirect('/settings')


@custom_admin_only
def users(request):
    users = User.objects.all()
    usernames_list = [{"id": user.id, "username": user.username, "access_level": user.is_superuser} for user in users]
    data = {"users": usernames_list}
    context = {
         "users": json.dumps(data),
         "section": "users"
    }
    return render(request, 'mainapp/users.html', context)


@custom_admin_only
def settings(request):
     sync = SyncInterval.objects.all()
     sync_intervals = [ip_obj.sync_interval for ip_obj in sync]

     if sync_intervals:
          sync_interval = int(sync_intervals[-1])
     else:
          sync_interval = 12

     ips = IPSpace.objects.all()
     ips_list = [{"id": ip.id, "ip": ip.ip_space, "description": ip.description} for ip in ips]

     context = {
          "section": "settings",
          "sync_interval": sync_interval,
          "ips_list": ips_list
     }
     return render(request, 'mainapp/settings.html', context)


@login_required(login_url='login')
def logout_user(request):
    user_ip = get_user_ip(request)
    device_info = get_device_info(request)
    username = request.user.username if request.user.is_authenticated else "Anonymous"
    auth_logger.info(f"200 OK {user_ip} {username} {request.path} {device_info}")
    logout(request)
    messages.success(request, "Successfully logged out")
    return HttpResponseRedirect('/')


@never_cache
def password_reset(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        # Check if the email exists in the database
        if User.objects.filter(email=email).exists():
            return auth_views.PasswordResetView.as_view()(request)
        else:
          messages.error(request, "Email not found")

    return render(request, 'mainapp/password_reset_form.html')


@never_cache
def password_reset_done(request):
    return auth_views.PasswordResetDoneView.as_view()(request)

@never_cache
def password_reset_confirm(request, uidb64, token):
    return auth_views.PasswordResetConfirmView.as_view()(request, uidb64=uidb64, token=token)


@never_cache
def password_reset_complete(request):
    return auth_views.PasswordResetCompleteView.as_view()(request)

@csrf_exempt
def github_webhook(request):
     if request.method == 'POST':
          payload = json.loads(request.body)
          event_type = request.headers.get('X-GitHub-Event')

          if event_type == 'push' and 'ref' in payload and payload['ref'] == 'refs/heads/staging':
              author_name = payload['pusher']['name']
              commit_message = payload['head_commit']['message']
              deploy_logger.info(f"Attempt to deployment: {author_name} - {commit_message} /{payload['ref']}")
              try:
                  subprocess.run(['/usr/bin/sudo', '/home/charles/ip-reputation/staging/ip-monitoring-tool/.github/workflows/deploy.sh'])
                  deploy_logger.info(f"Deployment: {author_name} - {commit_message} /{payload['ref']}")
              except subprocess.CalledProcessError as e:
                  deploy_logger.error(f"Error deploying from {author_name}/ {commit_message}: {e}")
              

     return HttpResponse(status=200)

mainapp/templates/mainapp/dashboard.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} 
{% block content %}
<div id="content">
  <div id="dashboard-header"><h2>Reputation Monitor</h2>
    <div class="your_ip">
      <p>Your IP:</p>
      <p id="my_ip"></p>
    </div>
    </div>

  <div class="search">
    <form method="post" id="myForm">
      {% csrf_token %}
    <select name="select_choice" id="id_select_choice">
      {% for value, label in form.fields.select_choice.choices %}
          <option value="{{ value }}" {% if value == form.cleaned_data.select_choice %}selected{% endif %}>{{ label }}</option>
      {% endfor %}
    </select>
    </form>
    <button class="btn" id="add_ip_btn">Add RENU IP Space</button>
  </div>

  <div id="overlay-dashboard">
    <form action="{% url 'add_ip_space' %}" method="post" id="add_user_form">
      {% csrf_token %}
      <h2>Add RENU IP Space</h2>
      <div class="input-fields-user">
        <label for="ip_space">IP space</label>
        <input type="text" name="ip_space" id="ip_space" placeholder="x.x.x.x/x" required />
      </div>
      <div class="input-fields-user">
        <label for="description">Description</label>
        <textarea name="description" id="description" cols="30" rows="10" placeholder="Enter description" required></textarea>
      </div>
  
      <div class="btn_group">
        <button type="button" class="btn cancel" id="cancel_btn">Cancel</button>
        <button type="submit" class="btn add">Add</button>
      </div>
    </form>
  </div>

    <div class="result" id="noDataMessage">
      <p>None of RENU IP is listed in <span id="selected_site">{{ selected_label }}</span> lists</p>
    </div>

    <table class="auto-group-p2pf-Vw7" id="ipTable">
      <thead class="frame-11-N7j">
        <tr>
          <th class="column-3Um">IP address</th>
          <th>Timestamp</th>
          <th class="column-2Lh">Site</th>
        </tr>
      </thead>
      <tbody>
        {% for value in blocklist %}
        <tr class="td-ASu">
          <td >{{ value.ip }}</td>
          <td>{{ value.timestamp }}</td>
          <td>{{ value.source }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


</div>

<!-- Add the JavaScript to handle the change event -->
<script data-blocklist="{{ blocklist }}" data-label="{{ selected_label }}" data-my_ip="{{ my_ip }}">
  const data = document.currentScript.dataset
  
  document.addEventListener('DOMContentLoaded', function() {
      const selectElement = document.getElementById('id_select_choice');
      const formElement = document.getElementById('myForm');
      const ipTable = document.getElementById('ipTable');
      const ipTableBody = document.getElementById('ipTable').querySelector('tbody');
      const noDataMessage = document.getElementById('noDataMessage')
      cancelBtn = document.getElementById("cancel_btn");
      addUserBtn = document.getElementById("add_ip_btn");
      const overlay = document.getElementById("overlay-dashboard");
      const myIP = document.getElementById("my_ip")

      addUserBtn.addEventListener("click", function (event) {
        overlay.style.display = "flex";
      });

      cancelBtn.addEventListener("click", function (event) {
        console.log("clicked");
        overlay.style.display = "none";
      });

      const blocklist = JSON.parse(data.blocklist)
      const selectedLabel = data.label
      const my_ip = data.my_ip

      if(my_ip){
        myIP.innerHTML = my_ip
      }

        let currentList = []
        if(selectedLabel === "All Databases"){
          currentList = blocklist
        } else {
          currentList = blocklist.filter(ip => ip.source === selectedLabel)
        }

        ipTableBody.innerHTML = '';

        if(currentList.length > 0){
          noDataMessage.style.display = 'none';
          currentList.forEach(entry => {
          const row = document.createElement('tr');
          const ipCell = document.createElement('td');
          ipCell.textContent = entry.ip;
          const timestampCell = document.createElement('td')
          timestampCell.textContent = entry.timestamp;
          const sourceCell = document.createElement('td');
          sourceCell.textContent = entry.source;
          row.appendChild(ipCell);
          row.appendChild(timestampCell)
          row.appendChild(sourceCell);
          ipTableBody.appendChild(row);
    });
        } else { 
          noDataMessage.style.display = 'block';
          ipTable.style.display = 'none'
        }
      
      selectElement.addEventListener('change', function (event) {
        event.preventDefault()
          // Submit the form automatically when an option is selected
          formElement.submit()
      });
  });
</script>
{% endblock %}

mainapp/templates/mainapp/logged_out.html
{% extends "base.html" %}
{% block title %}Logged Out {% endblock %}
{% block content %}
<div id="content">
    <h1>Logged out</h1>
    <p>
        You have been successfully logged out.
        You can <a href="{% url 'login' %}">log-in again</a>
    </p>
</div>
    {% endblock %}

mainapp/templates/mainapp/password_change_done.html
{% extends "base.html" %}

{% block title %}Password Changed{% endblock %}

{% block content %}
<div id="content">
    <h1>Password Changed</h1>
    <p>Your password has been changed successfully</p>
</div>
{% endblock %} 

mainapp/templates/mainapp/password_change_form.html
{% extends "base.html" %}

{% block title %}Change your password{% endblock %}

{% block content %}
<div id="content">
    <h1>Change your password</h1>
    <p>Use the form below to change your password</p>
    <form method="post">
        {{ form.as_p}}
        <p><input type="submit" value="Change"></p>
        {% csrf_token %}
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/password_reset_complete.html
{%extends 'base.html'%} {% block title %}Reset Password{% endblock %} 

{%block content%}
<div id="content">
    <h1>Password Changed</h1>
    <p>Your password has been changed successfully</p>
	<p><a href="{%url 'login'%}">Login </a></p>
</div>

{%endblock content%}

mainapp/templates/mainapp/password_reset_confirm.html
{%extends 'base.html'%} {% block title %}Reset Password{% endblock %} 
{%block content%}
<main class="login-form-container">
  <div class="login-form">
		<div class="login-welcome">
		  {% load static %}
		  <a href="{%url 'dashboard' %}" class=""
			><img
			  src="{% static 'renu_logo.png' %}"
			  width="80px"
			  alt="RENU Logo"
		  /></a>
		  <p>Password Reset Confirm</p>
		</div>
  <div class="center">
    <form method="post">
      {% csrf_token %}
      <div class="input-fields">
        <label for="">New Password</label>
        <div>
          <input
          type="password"
          class="form-control"
          placeholder="New Password"
          name="{{ form.new_password1.name }}"
          minlength="8"
          required
          />
        </div>
        </div>

        <div class="input-fields">
          <label for="">Confirm Password</label>
          <div>
            <input
            type="password"
            class="form-control"
            placeholder="Confirm Password"
            name="{{ form.new_password2.name }}"
            minlength="8"
            required
            />
          </div>
          </div>
  

      <input type="submit" value="Change Password" class="login-btn" />
    </form>
  </div>
</main>

{%endblock content%}

mainapp/templates/mainapp/password_reset_done.html
{%extends 'base.html'%} {% block title %}Reset Password{% endblock %} 

{%block content%}
<div id="content">
  <div class="center card">
    <h2>Reset Password</h2>
    <p>
      Please check your inbox and follow the instruction to reset your password.
    </p>
  </div>
</div>

{%endblock content%}

mainapp/templates/mainapp/password_reset_form.html
{%extends 'base.html'%} {% block title %}Reset Password{% endblock %} 

{%block content%}
<main class="login-form-container">
	<div class="login-form">
		<div class="login-welcome">
		  {% load static %}
		  <a href="{%url 'dashboard' %}" class=""
			><img
			  src="{% static 'renu_logo.png' %}"
			  width="80px"
			  alt="RENU Logo"
		  /></a>
		  <p>Reset Password</p>
		</div>
	<div class="center">
		<form method="post">
			{% csrf_token %}
				<div class="input-fields">
					<label for="">Email</label>
					<div>
					  <input
						type="email"
						class="form-control"
						placeholder="email"
						name="email"
						required
					  />
					</div>
				  </div>
		<input type="submit" value="Submit" class="login-btn" />
		</form>
		<p>
      <a href="{%url 'login' %}">Remember password? </a>
    </p>
		</div>
</main>
{%endblock content%}

mainapp/templates/mainapp/settings.html
{% extends "base.html" %} {% block title %}Settings{% endblock %} 
{% load static %} {% block extra_css %}
<link type="text/css" href="{% static 'css\settings.css' %}" rel="stylesheet" />
{% endblock %} {% block content %}
<div id="content">
  <h2>Settings</h2>
  <div class="frame-1-mKf">
    <p class="change-reputation-sync-interval-rc1">
      Change Reputation Sync Interval
    </p>
    <form method="post" id="myForm" action="{% url 'sync_interval' %}">
      {% csrf_token %}
      <div class="hours">
        <input
          class=""
          name="sync_interval"
          type="text"
          id="sync_interval"
          value="{{ sync_interval }}"
          required
        />
        <p>Hours</p>
      </div>
      <input class="btn" type="submit" value="Update" />
    </form>
  </div>

  <div id="overlay-dashboard">
    <form action="{% url 'edit_ip' 0 %}" method="post" id="editForm">
      {% csrf_token %}
      <h3>Edit RENU IP Space</h3>
      <div class="input-fields-user">
        <label for="ip_space">IP space</label>
        <input
          type="text"
          name="ip_space"
          id="edit_ip_input"
          placeholder="x.x.x.x/x"
          required
        />
      </div>
      <div class="input-fields-user">
        <label for="description">Description</label>
        <textarea
          name="description"
          id="edit_desc_input"
          cols="30"
          rows="10"
          placeholder="Enter description"
          required
        ></textarea>
      </div>

      <div class="btn_group">
        <button type="button" class="btn cancel" id="cancel_btn">Cancel</button>
        <button type="submit" class="btn add">Edit</button>
      </div>
    </form>
  </div>

  <div id="overlay-delete">
    <form action="{% url 'delete_ip' 0 %}" method="post" id="deleteForm">
      {% csrf_token %}
      <h3>Delete <span id="delete_ip"></span></h3>
      <p>Are you sure you want to delete this IP, this action is irreversible.</p>

      <div class="btn_group">
        <button type="button" class="btn cancel" id="cancel_btn_1">
          No, Cancel
        </button>
        <button type="submit" class="btn add">Yes, Delete</button>
      </div>
    </form>
  </div>

  <h2>IP Space Management</h2>

  <table class="auto-group-p2pf-Vw7" id="ipTable">
    <thead class="frame-11-N7j">
      <tr>
        <th class="column-3Um">IP Space</th>
        <th class="column-2Lh">Descripton</th>
        <th class="column-2Lh">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for value in ips_list %}
      <tr class="td-ASu">
        <td>{{ value.ip }}</td>
        <td>{{ value.description }}</td>
        <td>
          <button
            class="btn-icons"
            id="edit_ip_btn"
            onclick="editIP(' {{ value.id }} ', ' {{ value.ip|escapejs }} ', ' {{ value.description|escapejs }} ')"
          >
            <img src="{% static 'icons/edit.svg' %}" />
          </button>
          <button
            class="btn-icons"
            onclick="
          deleteIP('{{ value.id }}', '{{ value.ip }}')"
          >
            <img src="{% static 'icons/delete.svg' %}" />
          </button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<!-- Add the JavaScript to handle the change event -->
<script data-ips_list="{{ ips_list }}">
  const data = document.currentScript.dataset;

  const overlay = document.getElementById("overlay-dashboard");
  const deleteOverlay = document.getElementById("overlay-delete");

  const editIP = (id, ip, description) => {
    const editIpInput = document.getElementById("edit_ip_input");
    const editDescInput = document.getElementById("edit_desc_input");
    const form = document.getElementById('editForm');
    editIpInput.value = ip.trim();
    editDescInput.value = description.trim();

    const editUrl = `/edit_ip/${id.trim()}/`;

    // Update the form's action attribute
    form.action = editUrl;
    
    overlay.style.display = "flex";
  };

  const deleteIP = (id, ip) => {
    const ipToDelete = document.getElementById("delete_ip");
    const form = document.getElementById('deleteForm');
    ipToDelete.innerHTML = ip.trim()

    const editUrl = `/delete_ip/${id.trim()}/`;

    // Update the form's action attribute
    form.action = editUrl;

    deleteOverlay.style.display = "flex";
  };

  document.addEventListener("DOMContentLoaded", function () {

    const cancelBtn = document.getElementById("cancel_btn");
    const cancelBtn1 = document.getElementById("cancel_btn_1");

    cancelBtn.addEventListener("click", function (event) {
      overlay.style.display = "none";
    });

    cancelBtn1.addEventListener("click", function (event) {
      deleteOverlay.style.display = "none";
    });
  });
</script>
{% endblock %}

mainapp/templates/mainapp/too_many_attempts.html
{% extends "base.html" %} {% block title %}Login{% endblock %} 
{% block content%}

<main class="login-form-container">
  <div class="login-form">
    <div class="login-welcome">
      <p>Welcomejjjj</p>
    </div>

    <p>
      <a href="#">Forgot your Password? </a>
    </p>
  </div>
</main>

{% endblock %}